# Workflow derived from https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml
on:
  push:
    branches: [main]
    tags: ['*']

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., SeuratData=?ignore
          needs: website

      - name: Install SeuratData
        if: always()
        run: Rscript -e "install.packages('remotes', repos = 'http://cran.us.r-project.org'); remotes:::install_github('satijalab/seurat-data')"
        shell: bash

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
          git-config-name: ${{ github.actor }}
          git-config-email: ${{ github.actor }}@users.noreply.github.com
